version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
                NIGHTLY_DATE="$(date +%Y%m%d)"
                docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
                docker build --pull -t cennznet/rust-builder:latest -t cennznet/rust-builder:$NIGHTLY_DATE .
                docker push cennznet/rust-builder:$NIGHTLY_DATE
                docker push cennznet/rust-builder:latest
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 12 * * 0-4"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
